/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.algebra.rrrapp;

import hr.algebra.dao.model.User;
import hr.algebra.dao.model.UserRole;
import hr.algebra.rrrapp.view.Authentication;
import hr.algebra.rrrapp.view.EditAuthor;
import hr.algebra.rrrapp.view.EditComment;
import hr.algebra.rrrapp.view.EditPost;
import hr.algebra.rrrapp.view.Settings;
import hr.algebra.rrrapp.view.UploadContent;
import java.awt.Component;

/**
 *
 * @author miki
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        initTabs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpMain = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpMain, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Theme */
        com.formdev.flatlaf.intellijthemes.FlatSolarizedLightIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tpMain;
    // End of variables declaration//GEN-END:variables

    private Authentication authPanel;
    private UploadContent uploadPanel;
    private Settings settingsPanel;
    private EditPost editPost;
    private EditAuthor editAuthor;
    private EditComment editComment;
    
    private void initTabs() {
        authPanel = new Authentication();
        uploadPanel = new UploadContent();
        settingsPanel = new Settings();
        editPost = new EditPost();
        editAuthor = new EditAuthor();
        editComment = new EditComment();

        authPanel.setOnLoginSuccess(user -> {
            showTabsForUser(user);
            tpMain.remove(authPanel);
        });

        tpMain.add("Authenticate", authPanel);
    }

    private void showTabsForUser(User user) {
        tpMain.add("Upload", uploadPanel);
        tpMain.add("Edit Posts", editPost);
        tpMain.add("Edit Authors", editAuthor);
        tpMain.add("Edit Comments", editComment);
        tpMain.add("Settings", settingsPanel);

        if (user.getUserRoleId() == UserRole.ADMIN.getUserRole()) {
        }
    }
}
